var a = prompt("Введите а");
var b = prompt("Введите b");
console.log(a * b);
var r = prompt("Введите r");
console.log((4 / 3) * 3.14 * r * r * r);
var a = prompt("Введите a");
var h = prompt("Введите h");
console.log(a * h);
var a = prompt("Введите а");
var h = prompt("Введите h");
console.log(0.5 * a * h);
